# Generated by Django 5.0.6 on 2024-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_mobile_number', models.CharField(max_length=15)),
                ('pickup', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('Documents', 'Documents'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Furniture', 'Furniture'), ('Gifts', 'Gifts'), ('Health', 'Health & Beauty Products'), ('Office Supplies', 'Office Supplies'), ('Industrial Parts', 'Industrial & Automotive Parts'), ('Medical Supplies', 'Medical Supplies')], max_length=50)),
            ],
        ),
    ]
