# Generated by Django 5.0.6 on 2024-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortex_logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False, verbose_name='ID')
                 ),
                ('distance', models.FloatField()),
                ('weight', models.CharField(max_length=50)),
                ('delivery_charge', models.FloatField()),
            ],
        ),
    ]
