# Generated by Django 5.0.6 on 2024-06-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vortex_logistics_app', '0003_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='username',
            new_name='name',
        ),
    ]
