# Generated by Django 5.0.6 on 2024-06-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortex_logistics_app', '0004_rename_username_username_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_charge',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='weight',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
