# Generated by Django 5.0.6 on 2024-06-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortex_logistics_app', '0005_delivery_delivery_charge_delivery_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('Picked', 'Picked'), ('In_transist', 'In_transist'), ('Out_for_delivery', 'Out_for_delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=25, null=True),
        ),
    ]
